# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Controle de Produ��o INP-DENTOFLEX (800 x 400)jfHDev.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

import Logo_rc
import BackgroundVermelho_rc
import BackgroundPrincipalalpha_rc
import BackgroundFaltaOFalpha_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setWindowModality(Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 400)
        MainWindow.setMinimumSize(QSize(800, 400))
        MainWindow.setMaximumSize(QSize(800, 400))
        MainWindow.setFocusPolicy(Qt.NoFocus)
        MainWindow.setAcceptDrops(False)
        icon = QIcon()
        icon.addFile(u":/Logo/INP - DENTOFLEX (Preto).png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.000000000000000)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(u"")
        MainWindow.setIconSize(QSize(64, 60))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(800, 400))
        self.centralwidget.setMaximumSize(QSize(800, 400))
        self.BackgroundPrincipal = QFrame(self.centralwidget)
        self.BackgroundPrincipal.setObjectName(u"BackgroundPrincipal")
        self.BackgroundPrincipal.setGeometry(QRect(0, 0, 800, 400))
        self.BackgroundPrincipal.setMinimumSize(QSize(800, 400))
        self.BackgroundPrincipal.setMaximumSize(QSize(800, 400))
        self.BackgroundPrincipal.setMouseTracking(False)
        self.BackgroundPrincipal.setFocusPolicy(Qt.NoFocus)
        self.BackgroundPrincipal.setAcceptDrops(True)
        self.BackgroundPrincipal.setStyleSheet(u"image: url(:/BackgroundPrincipalalpha/Background principal alpha.png);")
        self.frameOF_Principal = QFrame(self.BackgroundPrincipal)
        self.frameOF_Principal.setObjectName(u"frameOF_Principal")
        self.frameOF_Principal.setGeometry(QRect(0, 0, 800, 400))
        self.frameOF_Principal.setStyleSheet(u"image: none;")
        self.frameOF_Principal.setFrameShape(QFrame.StyledPanel)
        self.frameOF_Principal.setFrameShadow(QFrame.Raised)
        self.frameOF_Principal.setLineWidth(1)
        self.OF_principal = QLineEdit(self.frameOF_Principal)
        self.OF_principal.setObjectName(u"OF_principal")
        self.OF_principal.setEnabled(True)
        self.OF_principal.setGeometry(QRect(410, 178, 171, 45))
        font = QFont()
        font.setFamily(u"Arial")
        font.setPointSize(32)
        self.OF_principal.setFont(font)
        self.OF_principal.setCursor(QCursor(Qt.IBeamCursor))
        self.OF_principal.setMouseTracking(True)
        self.OF_principal.setFocusPolicy(Qt.StrongFocus)
        self.OF_principal.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.OF_principal.setAcceptDrops(True)
        self.OF_principal.setToolTipDuration(0)
        self.OF_principal.setStyleSheet(u"background-color: None;\n"
"")
        self.OF_principal.setMaxLength(6)
        self.OF_principal.setFrame(True)
        self.OF_principal.setEchoMode(QLineEdit.Normal)
        self.OF_principal.setCursorPosition(0)
        self.OF_principal.setAlignment(Qt.AlignCenter)
        self.OF_principal.setDragEnabled(False)
        self.OF_principal.setReadOnly(False)
        self.OF_principal.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.OF_principal.setClearButtonEnabled(False)
        self.BackgroundVermelho = QFrame(self.centralwidget)
        self.BackgroundVermelho.setObjectName(u"BackgroundVermelho")
        self.BackgroundVermelho.setGeometry(QRect(0, 0, 800, 400))
        self.BackgroundVermelho.setMinimumSize(QSize(800, 400))
        self.BackgroundVermelho.setMaximumSize(QSize(800, 400))
        self.BackgroundVermelho.setStyleSheet(u"image: url(:/BackgroundVermelho/Background Vermelho.png);")
        self.frame_Parada = QFrame(self.BackgroundVermelho)
        self.frame_Parada.setObjectName(u"frame_Parada")
        self.frame_Parada.setGeometry(QRect(0, 0, 800, 400))
        self.frame_Parada.setFrameShape(QFrame.StyledPanel)
        self.frame_Parada.setFrameShadow(QFrame.Raised)
        self.cod_parada = QLineEdit(self.frame_Parada)
        self.cod_parada.setObjectName(u"cod_parada")
        self.cod_parada.setEnabled(True)
        self.cod_parada.setGeometry(QRect(380, 272, 40, 25))
        font1 = QFont()
        font1.setFamily(u"Arial")
        font1.setPointSize(14)
        font1.setBold(True)
        font1.setWeight(75)
        self.cod_parada.setFont(font1)
        self.cod_parada.setMouseTracking(True)
        self.cod_parada.setTabletTracking(True)
        self.cod_parada.setFocusPolicy(Qt.StrongFocus)
        self.cod_parada.setContextMenuPolicy(Qt.NoContextMenu)
        self.cod_parada.setAcceptDrops(True)
        self.cod_parada.setToolTipDuration(0)
        self.cod_parada.setMaxLength(2)
        self.cod_parada.setAlignment(Qt.AlignCenter)
        self.label_produto = QLabel(self.frame_Parada)
        self.label_produto.setObjectName(u"label_produto")
        self.label_produto.setGeometry(QRect(115, 146, 211, 16))
        font2 = QFont()
        font2.setFamily(u"Arial")
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setWeight(75)
        self.label_produto.setFont(font2)
        self.label_produto.setStyleSheet(u"image: None;")
        self.label_produto.setAlignment(Qt.AlignCenter)
        self.label_lote = QLabel(self.frame_Parada)
        self.label_lote.setObjectName(u"label_lote")
        self.label_lote.setGeometry(QRect(393, 193, 70, 16))
        self.label_lote.setFont(font2)
        self.label_lote.setStyleSheet(u"image: None;")
        self.label_lote.setAlignment(Qt.AlignCenter)
        self.label_medida = QLabel(self.frame_Parada)
        self.label_medida.setObjectName(u"label_medida")
        self.label_medida.setGeometry(QRect(418, 146, 57, 15))
        self.label_medida.setFont(font2)
        self.label_medida.setStyleSheet(u"image: None;")
        self.label_medida.setAlignment(Qt.AlignCenter)
        self.label_data = QLabel(self.frame_Parada)
        self.label_data.setObjectName(u"label_data")
        self.label_data.setGeometry(QRect(540, 146, 77, 15))
        self.label_data.setFont(font2)
        self.label_data.setStyleSheet(u"image: None;")
        self.label_data.setAlignment(Qt.AlignCenter)
        self.label_mat_pr = QLabel(self.frame_Parada)
        self.label_mat_pr.setObjectName(u"label_mat_pr")
        self.label_mat_pr.setGeometry(QRect(106, 193, 200, 16))
        self.label_mat_pr.setFont(font2)
        self.label_mat_pr.setStyleSheet(u"image: None;")
        self.label_mat_pr.setAlignment(Qt.AlignCenter)
        self.label_diam = QLabel(self.frame_Parada)
        self.label_diam.setObjectName(u"label_diam")
        self.label_diam.setGeometry(QRect(548, 193, 68, 15))
        self.label_diam.setFont(font2)
        self.label_diam.setStyleSheet(u"image: None;")
        self.label_diam.setAlignment(Qt.AlignCenter)
        self.label_status_parada = QLabel(self.frame_Parada)
        self.label_status_parada.setObjectName(u"label_status_parada")
        self.label_status_parada.setGeometry(QRect(10, 10, 781, 113))
        font3 = QFont()
        font3.setFamily(u"Arial")
        font3.setPointSize(38)
        font3.setItalic(False)
        self.label_status_parada.setFont(font3)
        self.label_status_parada.setStyleSheet(u"image: None;")
        self.label_status_parada.setAlignment(Qt.AlignCenter)
        self.label_maquina = QLabel(self.frame_Parada)
        self.label_maquina.setObjectName(u"label_maquina")
        self.label_maquina.setGeometry(QRect(639, 161, 150, 90))
        font4 = QFont()
        font4.setFamily(u"Arial")
        font4.setPointSize(25)
        font4.setBold(True)
        font4.setItalic(False)
        font4.setWeight(75)
        self.label_maquina.setFont(font4)
        self.label_maquina.setStyleSheet(u"image: None;")
        self.label_maquina.setLineWidth(1)
        self.label_maquina.setAlignment(Qt.AlignCenter)
        self.label_maquina.setWordWrap(False)
        self.frame_Status_Parada = QFrame(self.frame_Parada)
        self.frame_Status_Parada.setObjectName(u"frame_Status_Parada")
        self.frame_Status_Parada.setGeometry(QRect(0, 0, 800, 131))
        self.frame_Status_Parada.setStyleSheet(u"image: none;\n"
"background-color: rgb(255, 0, 0);\n"
"\n"
"")
        self.frame_Status_Parada.setFrameShape(QFrame.StyledPanel)
        self.frame_Status_Parada.setFrameShadow(QFrame.Raised)
        self.frame_Status_Parada.setLineWidth(1)
        self.label_operador = QLabel(self.frame_Parada)
        self.label_operador.setObjectName(u"label_operador")
        self.label_operador.setGeometry(QRect(6, 230, 130, 21))
        font5 = QFont()
        font5.setFamily(u"Arial")
        font5.setPointSize(28)
        font5.setItalic(False)
        self.label_operador.setFont(font5)
        self.label_operador.setStyleSheet(u"image: None;")
        self.label_operador.setLineWidth(1)
        self.label_operador.setAlignment(Qt.AlignCenter)
        self.label_operador.setWordWrap(False)
        self.cod_op = QLineEdit(self.frame_Parada)
        self.cod_op.setObjectName(u"cod_op")
        self.cod_op.setGeometry(QRect(136, 234, 50, 20))
        self.cod_op.setFont(font1)
        self.cod_op.setContextMenuPolicy(Qt.NoContextMenu)
        self.cod_op.setToolTipDuration(0)
        self.cod_op.setMaxLength(3)
        self.cod_op.setAlignment(Qt.AlignCenter)
        self.cod_qtd = QLineEdit(self.frame_Parada)
        self.cod_qtd.setObjectName(u"cod_qtd")
        self.cod_qtd.setGeometry(QRect(390, 234, 50, 20))
        self.cod_qtd.setFont(font1)
        self.cod_qtd.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.cod_qtd.setMaxLength(4)
        self.cod_qtd.setAlignment(Qt.AlignCenter)
        self.cod_refugo = QLineEdit(self.frame_Parada)
        self.cod_refugo.setObjectName(u"cod_refugo")
        self.cod_refugo.setGeometry(QRect(577, 234, 35, 20))
        self.cod_refugo.setFont(font1)
        self.cod_refugo.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.cod_refugo.setMaxLength(3)
        self.cod_refugo.setAlignment(Qt.AlignCenter)
        self.historico = QWidget(self.frame_Parada)
        self.historico.setObjectName(u"historico")
        self.historico.setGeometry(QRect(9, 303, 610, 78))
        self.historico.setStyleSheet(u"image: none;\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.gridLayout = QGridLayout(self.historico)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.historico_intervalo = QWidget(self.historico)
        self.historico_intervalo.setObjectName(u"historico_intervalo")
        self.historico_intervalo.setStyleSheet(u"")
        self.gridLayout_6 = QGridLayout(self.historico_intervalo)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_historico_intervalo = QLabel(self.historico_intervalo)
        self.label_historico_intervalo.setObjectName(u"label_historico_intervalo")
        self.label_historico_intervalo.setStyleSheet(u"background-color: rgb(125, 125, 125);")

        self.gridLayout_6.addWidget(self.label_historico_intervalo, 4, 0, 1, 1)

        self.label_historico_intervalo_porcentagem = QLabel(self.historico_intervalo)
        self.label_historico_intervalo_porcentagem.setObjectName(u"label_historico_intervalo_porcentagem")
        self.label_historico_intervalo_porcentagem.setStyleSheet(u"image: None;\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")

        self.gridLayout_6.addWidget(self.label_historico_intervalo_porcentagem, 2, 0, 1, 1)

        self.lcdNumber_historico_intervalo = QLCDNumber(self.historico_intervalo)
        self.lcdNumber_historico_intervalo.setObjectName(u"lcdNumber_historico_intervalo")
        font6 = QFont()
        font6.setFamily(u"Arial Black")
        font6.setPointSize(12)
        font6.setBold(False)
        font6.setItalic(False)
        font6.setWeight(10)
        self.lcdNumber_historico_intervalo.setFont(font6)
        self.lcdNumber_historico_intervalo.setLayoutDirection(Qt.LeftToRight)
        self.lcdNumber_historico_intervalo.setAutoFillBackground(False)
        self.lcdNumber_historico_intervalo.setStyleSheet(u"image: None;\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_historico_intervalo.setFrameShape(QFrame.Box)
        self.lcdNumber_historico_intervalo.setMidLineWidth(0)
        self.lcdNumber_historico_intervalo.setSmallDecimalPoint(False)
        self.lcdNumber_historico_intervalo.setDigitCount(9)
        self.lcdNumber_historico_intervalo.setMode(QLCDNumber.Dec)
        self.lcdNumber_historico_intervalo.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_historico_intervalo.setProperty("value", 0.000000000000000)
        self.lcdNumber_historico_intervalo.setProperty("intValue", 0)

        self.gridLayout_6.addWidget(self.lcdNumber_historico_intervalo, 1, 0, 1, 1)


        self.gridLayout.addWidget(self.historico_intervalo, 0, 3, 1, 1)

        self.historico_parada = QWidget(self.historico)
        self.historico_parada.setObjectName(u"historico_parada")
        self.historico_parada.setStyleSheet(u"")
        self.gridLayout_5 = QGridLayout(self.historico_parada)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_historico_parada = QLabel(self.historico_parada)
        self.label_historico_parada.setObjectName(u"label_historico_parada")
        self.label_historico_parada.setStyleSheet(u"background-color: rgb(255, 0, 0);")

        self.gridLayout_5.addWidget(self.label_historico_parada, 4, 0, 1, 1)

        self.label_historico_parada_porcentagem = QLabel(self.historico_parada)
        self.label_historico_parada_porcentagem.setObjectName(u"label_historico_parada_porcentagem")
        self.label_historico_parada_porcentagem.setStyleSheet(u"image: None;\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")

        self.gridLayout_5.addWidget(self.label_historico_parada_porcentagem, 2, 0, 1, 1)

        self.lcdNumber_historico_parada = QLCDNumber(self.historico_parada)
        self.lcdNumber_historico_parada.setObjectName(u"lcdNumber_historico_parada")
        self.lcdNumber_historico_parada.setFont(font6)
        self.lcdNumber_historico_parada.setLayoutDirection(Qt.LeftToRight)
        self.lcdNumber_historico_parada.setAutoFillBackground(False)
        self.lcdNumber_historico_parada.setStyleSheet(u"image: None;\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_historico_parada.setFrameShape(QFrame.Box)
        self.lcdNumber_historico_parada.setMidLineWidth(0)
        self.lcdNumber_historico_parada.setSmallDecimalPoint(False)
        self.lcdNumber_historico_parada.setDigitCount(9)
        self.lcdNumber_historico_parada.setMode(QLCDNumber.Dec)
        self.lcdNumber_historico_parada.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_historico_parada.setProperty("value", 0.000000000000000)
        self.lcdNumber_historico_parada.setProperty("intValue", 0)

        self.gridLayout_5.addWidget(self.lcdNumber_historico_parada, 1, 0, 1, 1)


        self.gridLayout.addWidget(self.historico_parada, 0, 2, 1, 1)

        self.historico_liberacao = QWidget(self.historico)
        self.historico_liberacao.setObjectName(u"historico_liberacao")
        self.historico_liberacao.setStyleSheet(u"")
        self.gridLayout_4 = QGridLayout(self.historico_liberacao)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_historico_liberacao = QLabel(self.historico_liberacao)
        self.label_historico_liberacao.setObjectName(u"label_historico_liberacao")
        self.label_historico_liberacao.setStyleSheet(u"background-color: rgb(255, 255, 0);")

        self.gridLayout_4.addWidget(self.label_historico_liberacao, 4, 0, 1, 1)

        self.label_historico_liberacao_porcentagem = QLabel(self.historico_liberacao)
        self.label_historico_liberacao_porcentagem.setObjectName(u"label_historico_liberacao_porcentagem")
        self.label_historico_liberacao_porcentagem.setStyleSheet(u"image: None;\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")

        self.gridLayout_4.addWidget(self.label_historico_liberacao_porcentagem, 2, 0, 1, 1)

        self.lcdNumber_historico_liberacao = QLCDNumber(self.historico_liberacao)
        self.lcdNumber_historico_liberacao.setObjectName(u"lcdNumber_historico_liberacao")
        self.lcdNumber_historico_liberacao.setFont(font6)
        self.lcdNumber_historico_liberacao.setLayoutDirection(Qt.LeftToRight)
        self.lcdNumber_historico_liberacao.setAutoFillBackground(False)
        self.lcdNumber_historico_liberacao.setStyleSheet(u"image: None;\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_historico_liberacao.setFrameShape(QFrame.Box)
        self.lcdNumber_historico_liberacao.setMidLineWidth(0)
        self.lcdNumber_historico_liberacao.setSmallDecimalPoint(False)
        self.lcdNumber_historico_liberacao.setDigitCount(9)
        self.lcdNumber_historico_liberacao.setMode(QLCDNumber.Dec)
        self.lcdNumber_historico_liberacao.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_historico_liberacao.setProperty("value", 0.000000000000000)
        self.lcdNumber_historico_liberacao.setProperty("intValue", 0)

        self.gridLayout_4.addWidget(self.lcdNumber_historico_liberacao, 1, 0, 1, 1)


        self.gridLayout.addWidget(self.historico_liberacao, 0, 1, 1, 1)

        self.historico_treinamento = QWidget(self.historico)
        self.historico_treinamento.setObjectName(u"historico_treinamento")
        self.historico_treinamento.setStyleSheet(u"")
        self.gridLayout_8 = QGridLayout(self.historico_treinamento)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.label_historico_treinamento_porcentagem = QLabel(self.historico_treinamento)
        self.label_historico_treinamento_porcentagem.setObjectName(u"label_historico_treinamento_porcentagem")
        self.label_historico_treinamento_porcentagem.setStyleSheet(u"image: None;\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")

        self.gridLayout_8.addWidget(self.label_historico_treinamento_porcentagem, 2, 0, 1, 1)

        self.label_historico_treinamento = QLabel(self.historico_treinamento)
        self.label_historico_treinamento.setObjectName(u"label_historico_treinamento")
        self.label_historico_treinamento.setStyleSheet(u"background-color: rgb(0, 170, 255);")

        self.gridLayout_8.addWidget(self.label_historico_treinamento, 4, 0, 1, 1)

        self.lcdNumber_historico_treinamento = QLCDNumber(self.historico_treinamento)
        self.lcdNumber_historico_treinamento.setObjectName(u"lcdNumber_historico_treinamento")
        self.lcdNumber_historico_treinamento.setFont(font6)
        self.lcdNumber_historico_treinamento.setLayoutDirection(Qt.LeftToRight)
        self.lcdNumber_historico_treinamento.setAutoFillBackground(False)
        self.lcdNumber_historico_treinamento.setStyleSheet(u"image: None;\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_historico_treinamento.setFrameShape(QFrame.Box)
        self.lcdNumber_historico_treinamento.setMidLineWidth(0)
        self.lcdNumber_historico_treinamento.setSmallDecimalPoint(False)
        self.lcdNumber_historico_treinamento.setDigitCount(9)
        self.lcdNumber_historico_treinamento.setMode(QLCDNumber.Dec)
        self.lcdNumber_historico_treinamento.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_historico_treinamento.setProperty("value", 0.000000000000000)
        self.lcdNumber_historico_treinamento.setProperty("intValue", 0)

        self.gridLayout_8.addWidget(self.lcdNumber_historico_treinamento, 1, 0, 1, 1)


        self.gridLayout.addWidget(self.historico_treinamento, 0, 5, 1, 1)

        self.historico_try_out = QWidget(self.historico)
        self.historico_try_out.setObjectName(u"historico_try_out")
        self.historico_try_out.setStyleSheet(u"")
        self.gridLayout_7 = QGridLayout(self.historico_try_out)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.label_historico_try_out_porcentagem = QLabel(self.historico_try_out)
        self.label_historico_try_out_porcentagem.setObjectName(u"label_historico_try_out_porcentagem")
        self.label_historico_try_out_porcentagem.setStyleSheet(u"image: None;\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);\n"
"")

        self.gridLayout_7.addWidget(self.label_historico_try_out_porcentagem, 2, 0, 1, 1)

        self.label_historico_try_out = QLabel(self.historico_try_out)
        self.label_historico_try_out.setObjectName(u"label_historico_try_out")
        self.label_historico_try_out.setStyleSheet(u"background-color: rgb(255, 0, 255);")

        self.gridLayout_7.addWidget(self.label_historico_try_out, 4, 0, 1, 1)

        self.lcdNumber_historico_try_out = QLCDNumber(self.historico_try_out)
        self.lcdNumber_historico_try_out.setObjectName(u"lcdNumber_historico_try_out")
        self.lcdNumber_historico_try_out.setFont(font6)
        self.lcdNumber_historico_try_out.setLayoutDirection(Qt.LeftToRight)
        self.lcdNumber_historico_try_out.setAutoFillBackground(False)
        self.lcdNumber_historico_try_out.setStyleSheet(u"image: None;\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_historico_try_out.setFrameShape(QFrame.Box)
        self.lcdNumber_historico_try_out.setMidLineWidth(0)
        self.lcdNumber_historico_try_out.setSmallDecimalPoint(False)
        self.lcdNumber_historico_try_out.setDigitCount(9)
        self.lcdNumber_historico_try_out.setMode(QLCDNumber.Dec)
        self.lcdNumber_historico_try_out.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_historico_try_out.setProperty("value", 0.000000000000000)
        self.lcdNumber_historico_try_out.setProperty("intValue", 0)

        self.gridLayout_7.addWidget(self.lcdNumber_historico_try_out, 1, 0, 1, 1)


        self.gridLayout.addWidget(self.historico_try_out, 0, 4, 1, 1)

        self.historico_producao = QWidget(self.historico)
        self.historico_producao.setObjectName(u"historico_producao")
        self.historico_producao.setStyleSheet(u"image: None;")
        self.gridLayout_2 = QGridLayout(self.historico_producao)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_historico_producao_porcentagem = QLabel(self.historico_producao)
        self.label_historico_producao_porcentagem.setObjectName(u"label_historico_producao_porcentagem")
        self.label_historico_producao_porcentagem.setStyleSheet(u"image: None;\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")

        self.gridLayout_2.addWidget(self.label_historico_producao_porcentagem, 2, 0, 1, 1)

        self.label_historico_producao = QLabel(self.historico_producao)
        self.label_historico_producao.setObjectName(u"label_historico_producao")
        self.label_historico_producao.setStyleSheet(u"background-color: rgb(0, 170, 0);")

        self.gridLayout_2.addWidget(self.label_historico_producao, 4, 0, 1, 1)

        self.lcdNumber_historico_producao = QLCDNumber(self.historico_producao)
        self.lcdNumber_historico_producao.setObjectName(u"lcdNumber_historico_producao")
        self.lcdNumber_historico_producao.setFont(font6)
        self.lcdNumber_historico_producao.setLayoutDirection(Qt.LeftToRight)
        self.lcdNumber_historico_producao.setAutoFillBackground(False)
        self.lcdNumber_historico_producao.setStyleSheet(u"image: None;\n"
"font: 87 12pt \"Arial Black\";\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_historico_producao.setFrameShape(QFrame.Box)
        self.lcdNumber_historico_producao.setMidLineWidth(0)
        self.lcdNumber_historico_producao.setSmallDecimalPoint(False)
        self.lcdNumber_historico_producao.setDigitCount(9)
        self.lcdNumber_historico_producao.setMode(QLCDNumber.Dec)
        self.lcdNumber_historico_producao.setSegmentStyle(QLCDNumber.Filled)
        self.lcdNumber_historico_producao.setProperty("value", 0.000000000000000)
        self.lcdNumber_historico_producao.setProperty("intValue", 0)

        self.gridLayout_2.addWidget(self.lcdNumber_historico_producao, 1, 0, 1, 1)


        self.gridLayout.addWidget(self.historico_producao, 0, 0, 1, 1)

        self.label_qtd = QLabel(self.frame_Parada)
        self.label_qtd.setObjectName(u"label_qtd")
        self.label_qtd.setGeometry(QRect(328, 230, 59, 21))
        self.label_qtd.setFont(font5)
        self.label_qtd.setStyleSheet(u"image: None;")
        self.label_qtd.setLineWidth(1)
        self.label_qtd.setAlignment(Qt.AlignCenter)
        self.label_qtd.setWordWrap(False)
        self.label_refugo = QLabel(self.frame_Parada)
        self.label_refugo.setObjectName(u"label_refugo")
        self.label_refugo.setGeometry(QRect(475, 230, 100, 21))
        self.label_refugo.setFont(font5)
        self.label_refugo.setStyleSheet(u"image: None;")
        self.label_refugo.setLineWidth(1)
        self.label_refugo.setAlignment(Qt.AlignCenter)
        self.label_refugo.setWordWrap(False)
        self.frame_Status_Parada.raise_()
        self.label_produto.raise_()
        self.label_lote.raise_()
        self.label_medida.raise_()
        self.label_data.raise_()
        self.label_mat_pr.raise_()
        self.label_diam.raise_()
        self.label_status_parada.raise_()
        self.label_maquina.raise_()
        self.label_operador.raise_()
        self.cod_op.raise_()
        self.cod_qtd.raise_()
        self.cod_refugo.raise_()
        self.cod_parada.raise_()
        self.historico.raise_()
        self.label_qtd.raise_()
        self.label_refugo.raise_()
        self.BackgroundFaltaOF = QFrame(self.centralwidget)
        self.BackgroundFaltaOF.setObjectName(u"BackgroundFaltaOF")
        self.BackgroundFaltaOF.setGeometry(QRect(0, 0, 800, 400))
        self.BackgroundFaltaOF.setMinimumSize(QSize(800, 400))
        self.BackgroundFaltaOF.setMaximumSize(QSize(800, 400))
        self.BackgroundFaltaOF.setFocusPolicy(Qt.NoFocus)
        self.BackgroundFaltaOF.setAcceptDrops(True)
        self.BackgroundFaltaOF.setStyleSheet(u"image: url(:/BackgroundFaltaOFalpha/Backgroud Aguardando OF. alpha.png);")
        self.frameOF_FaltaOF = QFrame(self.BackgroundFaltaOF)
        self.frameOF_FaltaOF.setObjectName(u"frameOF_FaltaOF")
        self.frameOF_FaltaOF.setGeometry(QRect(0, 0, 800, 400))
        self.frameOF_FaltaOF.setFrameShape(QFrame.StyledPanel)
        self.frameOF_FaltaOF.setFrameShadow(QFrame.Raised)
        self.OF_FaltaOF = QLineEdit(self.frameOF_FaltaOF)
        self.OF_FaltaOF.setObjectName(u"OF_FaltaOF")
        self.OF_FaltaOF.setEnabled(True)
        self.OF_FaltaOF.setGeometry(QRect(410, 178, 171, 45))
        self.OF_FaltaOF.setFont(font)
        self.OF_FaltaOF.setMouseTracking(True)
        self.OF_FaltaOF.setFocusPolicy(Qt.StrongFocus)
        self.OF_FaltaOF.setAcceptDrops(True)
        self.OF_FaltaOF.setToolTipDuration(0)
        self.OF_FaltaOF.setStyleSheet(u"background-color: None;\n"
"")
        self.OF_FaltaOF.setMaxLength(6)
        self.OF_FaltaOF.setEchoMode(QLineEdit.Normal)
        self.OF_FaltaOF.setAlignment(Qt.AlignCenter)
        self.OF_FaltaOF.setDragEnabled(False)
        self.OF_FaltaOF.setReadOnly(False)
        self.OF_FaltaOF.setCursorMoveStyle(Qt.LogicalMoveStyle)
        self.OF_FaltaOF.setClearButtonEnabled(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.BackgroundFaltaOF.raise_()
        self.BackgroundVermelho.raise_()
        self.BackgroundPrincipal.raise_()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"CONTROLE DE PRODU\u00c7\u00c3O - Vers\u00e3o Alpha", None))
#if QT_CONFIG(whatsthis)
        MainWindow.setWhatsThis(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(whatsthis)
        MainWindow.setWindowFilePath("")
#if QT_CONFIG(tooltip)
        self.OF_principal.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.OF_principal.setInputMask("")
        self.OF_principal.setPlaceholderText("")
        self.cod_parada.setInputMask("")
        self.label_produto.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600;\">PRODUTO</span></p></body></html>", None))
        self.label_lote.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600;\">LOTE</span></p></body></html>", None))
        self.label_medida.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600;\">MEDIDA</span></p></body></html>", None))
        self.label_data.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600;\">DATA</span></p></body></html>", None))
        self.label_mat_pr.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600;\">MAT. PR.</span></p></body></html>", None))
        self.label_diam.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600;\">DIAM</span></p></body></html>", None))
        self.label_status_parada.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:65pt; font-weight:600;\">STATUS PARADA</span></p></body></html>", None))
        self.label_maquina.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:22pt; font-weight:600;\">M\u00c1QUINA</span></p></body></html>", None))
        self.label_operador.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:792; color:#808080;\">OPERADOR:</span></p></body></html>", None))
        self.label_historico_intervalo.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">INTERVALO</span></p></body></html>", None))
        self.label_historico_intervalo_porcentagem.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">100%</span></p></body></html>", None))
        self.label_historico_parada.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">PARADA</span></p></body></html>", None))
        self.label_historico_parada_porcentagem.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">100%</span></p></body></html>", None))
        self.label_historico_liberacao.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">LIBERA\u00c7\u00c3O</span></p></body></html>", None))
        self.label_historico_liberacao_porcentagem.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">100%</span></p></body></html>", None))
        self.label_historico_treinamento_porcentagem.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">100%</span></p></body></html>", None))
        self.label_historico_treinamento.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">TREINAMENTO</span></p></body></html>", None))
        self.label_historico_try_out_porcentagem.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">100%</span></p></body></html>", None))
        self.label_historico_try_out.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">TRY OUT</span></p></body></html>", None))
        self.label_historico_producao_porcentagem.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">100%</span></p></body></html>", None))
        self.label_historico_producao.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">PRODU\u00c7\u00c3O</span></p></body></html>", None))
        self.label_qtd.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:792; color:#808080;\">QTD.:</span></p></body></html>", None))
        self.label_refugo.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:14pt; font-weight:792; color:#808080;\">REFUGO:</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.OF_FaltaOF.setToolTip(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><br/></p></body></html>", None))
#endif // QT_CONFIG(tooltip)
        self.OF_FaltaOF.setInputMask("")
        self.OF_FaltaOF.setPlaceholderText("")
    # retranslateUi

